apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crusoe-registry-token-rotator.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crusoe-registry-token-rotator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crusoe-registry-token-rotator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crusoe-registry-token-rotator.labels" . | nindent 4 }}
rules:
  # This role grants permission to get the Crusoe credentials secret
  # and to manage the target PAT token secret.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "crusoe-registry-token-rotator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crusoe-registry-token-rotator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crusoe-registry-token-rotator.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "crusoe-registry-token-rotator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

---
# Create Role/RoleBinding in each target namespace
{{- range $ns := .Values.targetSecret.namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "crusoe-registry-token-rotator.fullname" $ }}-{{ $ns }}
  namespace: {{ $ns }}
  labels:
    {{- include "crusoe-registry-token-rotator.labels" $ | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "crusoe-registry-token-rotator.fullname" $ }}-{{ $ns }}
  namespace: {{ $ns }}
  labels:
    {{- include "crusoe-registry-token-rotator.labels" $ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crusoe-registry-token-rotator.serviceAccountName" $ }}
    namespace: {{ $.Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "crusoe-registry-token-rotator.fullname" $ }}-{{ $ns }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}